In [5]:
from IPython import utils  
from IPython.core.display import HTML  
import os  
def css_styling():  
    """Load the CSS sheet 'custom.css' located in the directory"""
    styles = "<style>\n%s\n</style>" % (open('./custom.css','r').read())
    return HTML(styles)
css_styling()  

# Part 3 - Introduction to NumPy

At the contrary to languages like Matlab, IDL or Fortran, the support of powerfull array construct is not built-in in Python and requires an external library: _NumPy_.

NumPy (pronounced 'Numb-pie') is the standard library for dealing with numerical arrays in Python. This is the main foundation of the scientific Python ecosystem. 

In [6]:
# we need to import the NumPy library in order to use it
import numpy as np  

# NumPy arrays
NumPy provides a N-dimensional array class _ndarray_. 

NumPy implements this array structure in C (fast!) and provides a convenient Python interface (ease to use!). 

In [7]:
# to create a NumPy array, call array() on a sequence 
my_array = np.array([0,1,2,3,4])

print(my_array)

[0 1 2 3 4]


In [8]:
# A NumPy array is not a Python list. 
type(my_array)

numpy.ndarray

In [9]:
# It is more similar to a Matlab array :
my_array + 1

array([1, 2, 3, 4, 5])

In [10]:
# multiplication operator acts elements
my_array * 2

array([0, 2, 4, 6, 8])

NumPy provides a number of ways to create arrays, similar to Matlab functions:

    arange([start,] stop[, step,]) # NumPy version of Python's arange()
    zeros(shape) # array of 0
    ones(shape)  # array of 1
    empty(shape) # Simply allocate memory without assigning it. 
            # Usefull if you are going to owerwrite them
            
    # create even linearly or logarithmically spaced grid of points
    # between a lower and upper bound that is inclusive on both ends.        
    linspace()
    logspace()

In [11]:
# creating an array going from 42 up to 142 by steps of 10
np.arange(42, 142, 10) 

array([ 42,  52,  62,  72,  82,  92, 102, 112, 122, 132])

In [12]:
np.ones(4) # the shape can be a single number (=lenght)

array([ 1.,  1.,  1.,  1.])

In [13]:
np.zeros((2,2)) # or a N-dimensional tuple

array([[ 0.,  0.],
       [ 0.,  0.]])

In [14]:
np.empty((2,3,4))

array([[[  6.93933296e-310,   1.45441069e-316,   6.93933335e-310,
           6.93933331e-310],
        [  6.93933332e-310,   6.93931858e-310,   6.93933335e-310,
           6.93931858e-310],
        [  6.93933332e-310,   6.93931858e-310,   6.93933335e-310,
           6.93931858e-310]],

       [[  6.93933332e-310,   6.93931858e-310,   6.93933335e-310,
           6.93931858e-310],
        [  6.93933335e-310,   6.93931858e-310,   6.93933335e-310,
           6.93931858e-310],
        [  6.93933332e-310,   6.93931858e-310,   6.93933335e-310,
           6.93931858e-310]]])

In [15]:
# Pay attention that sum() and np.sum() are two different functions ! 
# The Python built-in function sum() acts on iterables (such as list, etc) 
# while the NumPy version of sum np.sum() acts on NumPy ndarray.
# Therefore, the latter being optimized, it is much more faster for large arrays. 
import random
N = 1000000
x = [random.random() for _ in range(N)] # Python list
xa = np.random.random_sample(N) #NumPy array

In [16]:
%%timeit
sum(x)

100 loops, best of 3: 18.1 ms per loop


In [17]:
%%timeit 
np.sum(xa)

1000 loops, best of 3: 763 µs per loop


## dtypes
Because the `ndarray` object has been conceived to be performant (fast) for numerical operations, it can't mix types (at the contrary of Python lists). 

A NumPy array is an homogenous block of data organized in a N-Dimensional grid. As a consequence, the type of a `ndarray` is fixed for all the elements of the array. 

The _dtype_ (for data type) is the most important `ndarray` attribute. The data type determines
the size and meaning of each element of the array.

The _dtypes_ all have string character codes, as a concise mechanism for specifying the
type. 

_Examples_: int, foat, complex, etc. Precision can be defined (int8, int32, in64, etc...)


In [18]:
my_array = np.array([1.5, 2, 5.9, 9.0]) # auto-guess
my_array.dtype

dtype('float64')

In [19]:
# forces dtype to integer
my_array = np.array([1.5, 2, 5.9, 9.0], dtype=int) 
print(my_array)
print(my_array.dtype)

[1 2 5 9]
int64


In [20]:
# note that 'j' or '1j' is the imaginary symbol in NumPy
my_array = np.array([1.5 + 5j, 2, 5.9 + 6*1j, 9.0], dtype=complex) 
print(my_array)
print(my_array.dtype)

[ 1.5+5.j  2.0+0.j  5.9+6.j  9.0+0.j]
complex128


# Mathematical Operations

In [21]:
# All mathematical operators (exp, log, sqrt, etc) or constants are included of the NumPy library. 
# They act on NumPy array and return NumPy arrays
x = np.linspace(-np.pi, np.pi, 101)
result = np.cos(x)
print(result)
type(result)

[ -1.00000000e+00  -9.98026728e-01  -9.92114701e-01  -9.82287251e-01
  -9.68583161e-01  -9.51056516e-01  -9.29776486e-01  -9.04827052e-01
  -8.76306680e-01  -8.44327926e-01  -8.09016994e-01  -7.70513243e-01
  -7.28968627e-01  -6.84547106e-01  -6.37423990e-01  -5.87785252e-01
  -5.35826795e-01  -4.81753674e-01  -4.25779292e-01  -3.68124553e-01
  -3.09016994e-01  -2.48689887e-01  -1.87381315e-01  -1.25333234e-01
  -6.27905195e-02   2.83276945e-16   6.27905195e-02   1.25333234e-01
   1.87381315e-01   2.48689887e-01   3.09016994e-01   3.68124553e-01
   4.25779292e-01   4.81753674e-01   5.35826795e-01   5.87785252e-01
   6.37423990e-01   6.84547106e-01   7.28968627e-01   7.70513243e-01
   8.09016994e-01   8.44327926e-01   8.76306680e-01   9.04827052e-01
   9.29776486e-01   9.51056516e-01   9.68583161e-01   9.82287251e-01
   9.92114701e-01   9.98026728e-01   1.00000000e+00   9.98026728e-01
   9.92114701e-01   9.82287251e-01   9.68583161e-01   9.51056516e-01
   9.29776486e-01   9.04827052e-01

numpy.ndarray

# Slicing
NumPy arrays have the same slicing semantics as Python list.

In [22]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
a[2:6] # from the third element to the 6th (excluded) by stride of 1 

array([2, 3, 4, 5])

In [24]:
a[1::3] # from the second element to the last by stride of 3

array([1, 4, 7])

NumPy array can be N-dimensional, so you may slice along any and all axes. You can even use multiple axes. 

In [25]:
# create a 4x4 matrix
a = np.arange(16)
a.shape = (4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
# all the elements of the second row
a[1,:]

array([4, 5, 6, 7])

In [27]:
# all the elements of the second column
a[:,1]

array([ 1,  5,  9, 13])

In [28]:
# the first and third rows and third to fourth column
a[[0,2], 2:4]

array([[ 2,  3],
       [10, 11]])

__Pay attention:__ slides are _views_ of the original array. 

The data are to copied when a slide is made -> NumPy fast for slicing operations.

But it means that modification of their elements are reflected back in the original array!

In [29]:
print(a)
a[1:3,1:3] = -1
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4 -1 -1  7]
 [ 8 -1 -1 11]
 [12 13 14 15]]


# ndarray attributes and methods
The `ndarray` type is - as everything in Python - an object, with several attributes: 

In [30]:
# number of dimensions (int)
a.ndim

2

In [31]:
# Tuple of integers that represents the rank along each dimensions
a.shape

(4, 4)

In [32]:
# total number of elements (int)
a.size

16

As well as several methods. 

In [33]:
a.reshape((2,8))

array([[ 0,  1,  2,  3,  4, -1, -1,  7],
       [ 8, -1, -1, 11, 12, 13, 14, 15]])

In [34]:
b=np.array([1,4,70,2,5,8])
# get the indice where the maximum value is 
b.argmax()

2

In [35]:
a.max()

15

In [36]:
# matrix multiplication 
a.dot(a)

array([[ 56,  36,  39,  74],
       [ 72,  97, 108,  99],
       [120, 153, 172, 171],
       [344, 180, 207, 506]])

In [37]:
a.sum()

86

__Pay attention__: 
 
 * Operations that involve attributes or methods of `ndarray` occur _in-place_. While functions that take an `ndarray` as an argument return a modified copy.
 * With NumPy `ndarray`, a=b creates a new _reference_ to b, not a _copy_. 
 

In [38]:
b=a # b is a new reference to a.
b[0]=10
print(b)

[[10 10 10 10]
 [ 4 -1 -1  7]
 [ 8 -1 -1 11]
 [12 13 14 15]]


In [39]:
# Because b refers to a, modifyng b also modify a !
print(a)

[[10 10 10 10]
 [ 4 -1 -1  7]
 [ 8 -1 -1 11]
 [12 13 14 15]]


In [40]:
b=a.copy() 
b[0] = 20
print(b)
print(a) # a has not been modified.

[[20 20 20 20]
 [ 4 -1 -1  7]
 [ 8 -1 -1 11]
 [12 13 14 15]]
[[10 10 10 10]
 [ 4 -1 -1  7]
 [ 8 -1 -1 11]
 [12 13 14 15]]


# Broadcasting
Broadcasting rules describe how arrays with different dimensions and/or shapes can be used for computations.

The general rule is that: 2 dimensions are compatible when they are equal or when one of them is 1.

![NumPy Broadcasting image 1](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

![NumPy Broadcasting Image 2](https://scipy-lectures.github.io/_images/numpy_broadcasting.png)

As an example, we calculate the outer product of two array, i.e.:
$$
    \mathbf{u} \otimes \mathbf{v} = \mathbf{u} \mathbf{v}^\mathrm{T} = \begin{bmatrix}u_1 \\ u_2 \\ u_3 \\ u_4\end{bmatrix} \begin{bmatrix}v_1 & v_2 & v_3\end{bmatrix} = \begin{bmatrix}u_1v_1 & u_1v_2 & u_1v_3 \\ u_2v_1 & u_2v_2 & u_2v_3 \\ u_3v_1 & u_3v_2 & u_3v_3 \\ u_4v_1 & u_4v_2 & u_4v_3\end{bmatrix}. $$

In [41]:
x = np.arange(4) # x.shape is (4,)
y = np.arange(3)  # y.shape is (3,)
# outer product
x.reshape(4,1) * y  # also possible : x[:, np.newaxis] * y 
                    # newaxis index operator inserts a new axis into x
                    # making it a two-dimensional 4x1 array. 

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

# Fancy Indexing, masking
Slicing is great when indices follow a regulary pattern. 

But when one want arbitrary indexes, this is known as _fancy indexing_: the index is an integer array or a list of integer.

This requires a _copy_ of the original array (so a performance cost)

In [42]:
a = np.arange(10)
print(a)

index = [3,1,6]
print(a[index])

[0 1 2 3 4 5 6 7 8 9]
[3 1 6]


_Masking_ is like fancy indexing, except that it _must_ be a Boolean array (not a Python list!). 

As with fancy indexing, the application of a mask to an array will produce a _copy_ of the original data. 

In [43]:
mask = np.array([0,1,0,1,1,0], dtype=bool)
a[mask]
# a[[0,1,0,1,1,0]] would not work, as one could expect from Matlab behaviour ! 

/usr/lib/python2.7/site-packages/ipykernel/__main__.py:2: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 6
  from ipykernel import kernelapp as app


array([1, 3, 4])

In [44]:
# The mask can be generated in the indexing operation itself
a[a > 5]

array([6, 7, 8, 9])

In [45]:
# It is also possible to combine masks with operators
a[(a>5) & (a<=8)]

array([6, 7, 8])

In [46]:
# the NumPy where() function takes a Boolean array 
# and return a tuple of the indices where the mask is True.
np.where(a > 5)

(array([6, 7, 8, 9]),)