# Partie II. Repéter des actions
## objectifs
<div class='objectives'> 

 <ul> 
     <li>Expliquer ce qu est une liste</li> 
     <li>Expliquer les boucles en Python</li>
     <li>Réaliser des boucles pour répéter des calculs simples</li>
 </ul>

</div>

In [109]:
import numpy as np

## Listes
Regardons le résultats 'infos' renvoyé précedemment par tsbase :

In [110]:
infos = ['test', 123, 'pif']
>>> type(infos)

list

C'est une liste. Les listes sont une manière de stocker plusieurs valeurs. Contrairement aux tableaux Numpy arrays, les listes Python sont livrées avec Python (pas besoin d'importer une librairie). Pour créer une liste, on mets des valeurs entre crochets :

In [111]:
impairs = [1, 3, 5, 7]
print(impairs) 

[1, 3, 5, 7]


Les éléments d une liste peuvent être de type différents : 

In [112]:
ma_liste = [42, 'pouet', 3.14]

Les élements d'une liste sont accessible avec des indices, comme pour les chaines de caractere:

In [113]:
ma_liste[1]

'pouet'

In [114]:
ma_liste[0:2]

[42, 'pouet']

Il est possible de modifier un élement d'une liste : 

In [115]:
impairs[2] = 42

A noter qu'il n est pas possible de modifier un élement d'une string: il faut créer une nouvelle string à la place.
→ modification in place ; notion de mutable (list, array) et immutable (string, numbers). 

__Attention__ : si deux variables se réferent à la même liste (mutable), changer l'une changera l autre ! 

In [116]:
ma_liste = [1,2,3,4,5]
print(ma_liste) 

[1, 2, 3, 4, 5]


In [117]:
>>> a = ma_liste
>>> a[2]=42
>>> print(a) # ok

[1, 2, 42, 4, 5]


In [118]:
>>> print(ma_liste) # attention !

[1, 2, 42, 4, 5]


Si on veut que ces variables soient independantes, il faut en faire des copies en créant une nouvelle liste :

In [119]:
ma_liste = [1, 2, 3, 4, 5]
a = list(ma_liste)
a[2]=42
print(a)
print(ma_liste)

[1, 2, 42, 4, 5]
[1, 2, 3, 4, 5]


idem avec des tableaux Numpy :

In [120]:
>>> mon_array = np.array([1,2,3,4,5])
>>> a = mon_array
>>> a[2]=42
>>> print(mon_array)
>>> print(a)

[ 1  2 42  4  5]
[ 1  2 42  4  5]


In [121]:
>>> mon_array = np.array([1,2,3,4,5])
>>> a = mon_array.copy()
>>> a[2]=42
>>> print(mon_array)
>>> print(a)

[1 2 3 4 5]
[ 1  2 42  4  5]


__Pourquoi?__ → performance en tête, quand les listes sont très grandes. 

Pour ajouter un élement à une liste existante :

In [122]:
ma_liste.append(100)
print(ma_liste)

[1, 2, 3, 4, 5, 100]


Avec la méthode `apend()`, on ajoute directement à la dernière position de la liste : très pratique dans les boucles.

Pour supprimer un élement de la liste (et renvoyer sa valeur), la méthode `pop()`:

In [123]:
ma_liste.pop(0) # or : del ma_liste[0]
print(ma_liste)

[2, 3, 4, 5, 100]


Pour insérer un élement dans une liste, la méthode `insert()`:

In [124]:
ma_liste.insert(3, 'test')
print(ma_liste)


[2, 3, 4, 'test', 5, 100]


Les listes ont un certain nombre de méthodes et attributs, cf:

    dir(ma_liste)

 - remove(value) : supprime la première occurence de `value` 
 - count(value) : compte le nombre d'occurences d'une valeur `value`.
 - sort() : tri
 
etc.

Nombre d'élements d'une liste :

In [125]:
len(ma_liste)

6

<div class='exercice'><h1>Exercice</h1>
Créez une liste et modifiez ses élements. Ajouter des élements (append, insert), supprimez-en (del)
</div>

## Tuples
Un tuple c'est comme une liste, sauf qu'elle est immutable : on ne peut pas changer un tuple apres sa création. Pour créer un tuple : parentheses

In [126]:
un_tuple = (1, 2, 3)

Pour les indices on utilise toujours les crochets []

__Attention__ : un tuple avec un seul element necessite une virgule avant de fermer la parenthèse :

In [127]:
un_tuple_simple = (1, )

car sinon, Python considera que c est autre chose qu'un tuple (ici un entier)

In [128]:
type( (1) )

int

In [129]:
type( (1,) ) 

tuple

Bonne nouvelle : on a pas besoin de mettre les parenthese, le contexte est suffisant.

In [130]:
un_tuple = 1, 2, 3

et là, vous reconnaissez le multi-assignement de tout à l'heure: 

In [131]:
un, deux, trois = 1, 2, 3

En fait, les fonctions renvoient des tuples. Ils permettent aux fonctions de retourner plusieurs variables. 

En fonction du contexte, Python va "dépaqueter" (unpack) les tuples dans les variables :

In [133]:
un = 1,2,3
print(un)
un, deux = 1,2,3

(1, 2, 3)


ValueError: too many values to unpack (expected 2)

→ Python s'attend à avoir trois variables et n'en trouve que deux : erreur !

* revenir sur PyWED : combien de variable en sortie ? 
* Prendre deux exemples avec 3 ou 4 output : SIPMES, GPHYB
* expliquer le nargout=2
* faire un exemple.

<div class='exercice'><h1>Exercice</h1>
Récupérez votre signal favori (avec ou sans nargout=)
</div>

## Boucles for
Supposons que l'on souhaite itérer sur les caractères d'une chaîne ou bien sur les élements d'une liste. La syntaxe d'une boucle for en Python est la suivante :

    for variable in collection:
         do things with variable...

Notez deux choses : 
 - le ":" 
 - l'indentation : tout ce qui est dans la boucle est indenté
 
En Python on *doit* indenter tout ce qui doit être inclus dans la boucle. Contrairement à beaucoup d'autres langages, il n'y a pas de commande ni de caractère spécial pour mettre fin à une boucle ({}, end for). 
Traditionnally, 4 spaces per level are used to indent all block codes. (No TAB !)

It is a codification of what is a best practice cording style in many other langages.

In [134]:
liste = [10,20,30,40,50]
for x in liste:
    print(x)

10
20
30
40
50


<div class='exercice'><h1>Exercice</h1>
Une chaine de caractère, peut être parcourue caractères par caractères dans une boucle! Réalisez une boucle for qui affiche chaque caractère d'une chaîne à partir de l'exemple précédent.
</div>

In [135]:
word = 'fusion'
for char in word:
    print(char)

f
u
s
i
o
n


Voici un autre exemple de boucle qui modifie une variable. 

In [136]:
length = 0
for vowel in 'aeiou':
    length = length + 1
print('There are', length, 'vowels')

There are 5 vowels


On peut utiliser le 'dépaquetage' pour simplifier le parcous des listes plus complexes:

In [137]:
couples = [[1,10], [2,20], [3,30], [4,40]]
print(couples)

[[1, 10], [2, 20], [3, 30], [4, 40]]


In [138]:
for (idx,val) in couples:
    print(idx, val)

1 10
2 20
3 30
4 40


En calcul numérique, on a souvent besoin de l'index du tableau. La fonction enumerate renvoie l'index et la valeur:

In [139]:
liste = ['test', 29797, 'GPHYB']
for idx, val in enumerate(liste):
    print(idx, val)

0 test
1 29797
2 GPHYB


**NB**:A very strong idiom in Python is to use a singular noun for the loop variable name and a plural noun for the iterable variable:

    for shot in shots:
    

<div class='exercice'>
<h1>Exercice</h1>
Réalisez une boucle qui récupère des signaux TS de plusieurs chocs, pour les enregistre dans une liste. 
Aide : avant d'écrire dans une liste, il faut que cette dernière existe au préalable (elle peut être vide). exemple = [].
</div>

In [140]:
shots = [47979, 47978, 47981]
sig = []
time = []
for shot in shots:
    sig.append(np.ones((1,100)))
    time.append(np.ones((1,100)))
    
print(time)
print(len(time))

[array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]), array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,

## Boucles While

Fontionnement similaire aux boucles for:

In [141]:
a = 5
while a != 0:
    a -= 1
    print(a)

4
3
2
1
0


## Conditions

Les tests (if) fonctionnent eux-aussi en indendant le code (n'oubliez pas le : !)

In [142]:
shot_exist = True
if shot_exist:
    print('The shot exists.')

The shot exists.


In [143]:
user_choice = 'no'
# there is no switch/case operators in Python. Use if/elif/else :
if user_choice == 'yes':
    print('yes')
elif user_choice in ('no', 'N'): # more elegant way to test inclusion
    print('no')
else:
    print('bad answer. Should be yes or no !')

no


<div class='exercice'><h1>Exercice</h1>
Réalisez une condition pour tester la valeur maximum du courant plasma d'un choc.
</div>

## Fonctions

* Function blocks are also defined using indentation and the `def` keyword.

In [144]:
def f(x):
    return x**2

f(4)

16

* A function can take zero, one or infinite input arguments.
* Optionnal input arguments with *default values* can be defined (*keyword* argument)

In [145]:
def g(a, b, c=1):
    print(a,b,c)

g(1,2)
g(1,2,3)

1 2 1
1 2 3


* A function can only returns *one* variable (a tuple in fact!)
* but this tuple can contain multiple valules !

In [146]:
def g(a,b,c=1):
    # returns a Tuple of two values. 
    # Could be written (a*2, a+b+c) as well. 
    return a*2, a+b+c 
print(g(1,2)) # assumes c=1
print(g(1,2,3))

(2, 4)
(2, 6)


<div class='exercice'><h1>Exercice</h1>
Créez une fonction qui retourne y=a*x+b en donnant a et b. Appliquez cette fonction à une liste de nombres.
</div>

In [147]:
def y(x,a=2,b=1):
    y = a*x + b
    return y

vals = [1,2,3,4,5]
new_vals = []

for val in vals:
    new_vals.append(y(val))
    
print(vals, new_vals)    

[1, 2, 3, 4, 5] [3, 5, 7, 9, 11]


* Also possible: a variable number of arguments

In [148]:
def h(*x):
    print(x)

h(1)
h(1, 'fusion', [1,2,3])

(1,)
(1, 'fusion', [1, 2, 3])


* Or using a variable number of keyword arguments (paramètres nommés)

In [149]:
def h2(*args, **kwargs):
    print(args, kwargs)
h2(1, 5, 6)    
h2([1,2,3], 'yes', option='test')

(1, 5, 6) {}
([1, 2, 3], 'yes') {'option': 'test'}


## Dictionnary

Un dictionnaire est un objet python qui permet d'associer à une clef (*key*) une valeur. Une clef peut être soit une chaine de caractère soit un nombre. Pour créer un dictionnaire on utilise les symboles {}
Exemples:

In [150]:
my_dict = {} # ou dict()
print(my_dict)
type(my_dict)

{}


dict

In [151]:
my_dict = {'nom':'Hillairet', 
           'prenom':'Julien', 
           'date_naissance': [1981,11,20], 
           1: 3.14, 
           1.7: 124}
print(my_dict)

{1: 3.14, 'date_naissance': [1981, 11, 20], 'nom': 'Hillairet', 'prenom': 'Julien', 1.7: 124}


On accède aux valeurs du dictionnaire à partir de sa clef : 

In [152]:
my_dict['nom']

'Hillairet'

In [153]:
my_dict[1]

3.14

Il est possible de créer de nouvelles combinaisons clef/valeurs à la volée :

In [154]:
my_dict['nb_de_kangoo'] = 1

On peut parcourir tous les élements d'un dictionnaire de plusieurs façon. Si on fait une boucle sur la liste, on va parcourir les clefs:

In [155]:
for item in my_dict: # one could write also my_dict.keys()
    print(item)

1
nb_de_kangoo
1.7
date_naissance
nom
prenom


Notez que l'ordre de parcours est totalement imprévisible, c'est normal car les dictionnaires ne sont pas des structures *ordonnées*. Pour parcourir les valeurs:

In [156]:
for val in my_dict.values():
    print(val)

3.14
1
124
[1981, 11, 20]
Hillairet
Julien


Enfin, pour parcourir à la fois les clefs et les valeurs, on utilise la méthode `items()`, qui renvoie le dictionnaire sous la forme d'une liste de tuples :

In [157]:
my_dict.items()

dict_items([(1, 3.14), ('nb_de_kangoo', 1), (1.7, 124), ('date_naissance', [1981, 11, 20]), ('nom', 'Hillairet'), ('prenom', 'Julien')])

In [158]:
for (key,val) in my_dict.items():
    print(key, ' --> ', val)   

1  -->  3.14
nb_de_kangoo  -->  1
1.7  -->  124
date_naissance  -->  [1981, 11, 20]
nom  -->  Hillairet
prenom  -->  Julien


Les dictionnaires ont de nombreuses méthodes, comme par exemple :

In [159]:
# Pour ajouter ou MàJ une valeur:
my_dict.update({'quote':"""Don't believe every quote 
           you read on the internet, because I totally didn't say that.
           Einstein."""})

# remove specified key and return the corresponding value.
# and returns it 
my_dict.pop(1) # or del my_dict[1]

3.14

In [160]:
my_dict

{'quote': "Don't believe every quote \n           you read on the internet, because I totally didn't say that.\n           Einstein.",
 'nb_de_kangoo': 1,
 1.7: 124,
 'date_naissance': [1981, 11, 20],
 'nom': 'Hillairet',
 'prenom': 'Julien'}

Les paramètres nommés d'une fonction sont en fait un dictionnaire:

In [161]:
def coucou(**parametres):
    print(parametres)
    
coucou(a=1, b=2, c='salut')

{'c': 'salut', 'a': 1, 'b': 2}


Les clefs des dictionnaires peuvent également être des tuples, utile pour créer des conteneur à "plusieurs dimensions" comme :

In [162]:
chocs_utiles = {}
chocs_utiles[47979, 'ip'] = 42
chocs_utiles[47979, 'LH'] = True
print(chocs_utiles)

{(47979, 'ip'): 42, (47979, 'LH'): True}


In [163]:
chocs_utiles[(47979)]

KeyError: 47979

In [164]:
chocs_utiles[(47979, 'ip')]

42

<div class='exercice'><h1>Exercice</h1>
Créez une liste de numéro de choc et une liste de noms de signaux. Pour chacun des chocs, récupérez les signaux correspondant aux noms de signaux et stocker le tout dans un dictionnaire avec des clefs (choc,signame).
</div>

In [180]:
chocs = [47979, 47982]
signames = ['SIPMES', 'GPHYB']
ma_base = dict() # ou {}

for choc in chocs:
    for signame in signames:
        y,t = 1,2#tsbase(choc, signame, nargout=2)
        ma_base[(choc, signame, 't')] = t
        ma_base[(choc, signame, 'val')] = val

In [165]:
from IPython import utils  
from IPython.core.display import HTML  
import os  
def css_styling():  
    """Load the CSS sheet 'custom.css' located in the directory"""
    styles = "<style>\n%s\n</style>" % (open('./custom.css','r').read())
    return HTML(styles)
css_styling()  