# Introduction à NumPy
Les listes Python montrent vite leur limitation en ce qui concerne le calcul scientifique:

In [6]:
liste = [1,2,3,4]

In [5]:
liste + 1

TypeError: can only concatenate list (not "int") to list

In [7]:
liste * 2

[1, 2, 3, 4, 1, 2, 3, 4]

En effet, contrairement à Matlab et IDL, le support des tableaux multidimensionels numériques n'est pas inclus dans le coeur du langage. 
 

## NumPy arrays

C'est pourquoi il existe une librairie, NumPy, qui permet de faire cela. NumPy est la brique de base à tout l'écosystème scientifique de Python.

In [1]:
import numpy as np

NumPy propose un type de tableau numérique N-dimensions : `array`. L'implémentation de NumPy repose sur du C (transparent) et est donc performante. L'interface utilisateur est très proche de celle de Matlab : 

In [3]:
# to create a NumPy array, call array() on a sequence 
my_array = np.array([0,1,2,3,4])

print(my_array)
print(type(my_array))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
my_array + 1

array([1, 2, 3, 4, 5])

In [9]:
my_array * 2

array([0, 2, 4, 6, 8])

In [10]:
my_array ** 2

array([ 0,  1,  4,  9, 16])

Parce que les array NumPy ont été conçus avec la problématique de la performance en tête, les array NumPy ont plusieurs propriétés spécifiques :

* Contrairement aux listes Python, on ne peut pas mélanger les types dans un tableau array NumPy

* Le type de données numériques peut être indiqué si besoin:

In [47]:
np.array([1.1, 2.2, 3.3]) # auto-guess 

array([ 1.1,  2.2,  3.3])

In [50]:
np.array([1.1, 2.2, 3.3]).dtype

dtype('float64')

In [51]:
np.array([1.1, 2.2, 3.3], dtype='int') # casting into int

array([1, 2, 3])

In [53]:
np.array([1.1, 2.2, 3.3], dtype='complex') 
# note that 1j or j is the imaginary unit in Python

array([ 1.1+0.j,  2.2+0.j,  3.3+0.j])

In [73]:
array1 = np.arange(0, 9).reshape((3,3))
array2 = np.arange(9, 0, -1).reshape((3,3))
array1 + array2

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

**attention** : contrairement à matlab, l'opérateur * sur des tableaux NumPy effectue le produit élément par élément:

In [74]:
array1 * array2

array([[ 0,  8, 14],
       [18, 20, 20],
       [18, 14,  8]])

In [76]:
array1 * np.eye(3)

array([[ 0.,  0.,  0.],
       [ 0.,  4.,  0.],
       [ 0.,  0.,  8.]])

Le produit matriciel (où produit *intérieur*) est obtenu avec la fonction `dot` :

In [75]:
np.dot(array1, array2)

array([[ 12,   9,   6],
       [ 66,  54,  42],
       [120,  99,  78]])

In [77]:
array1.dot(np.eye(3))

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

## Fonctions utiles

Tout comme Matlab, NumPy proposes de nombreuses fonctions permettant de créer et éventuellement d'allouer des tableaux :

In [12]:
np.arange(0, 10, 1) # start, stop, step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.zeros((5,3)) # the shape is a tuple

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
np.linspace(0, 10, num=6)

array([  0.,   2.,   4.,   6.,   8.,  10.])

NumPy also provides all mathematical functions which are compatible with NumPy N-D arrays :

In [21]:
array = np.arange(0,9)
print(array)

[0 1 2 3 4 5 6 7 8]


In [72]:
array.shape
# also : ndim, size (!=matlab)

(9,)

In [23]:
array.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
array.min()

(0, 8)

In [26]:
array.max()

8

In [35]:
# 9 random integers between 0 (included) to 10 (excluded)
array = np.random.randint(0, 10, 9)
print(array)

[2 0 9 4 5 6 9 5 0]


In [36]:
# get the array index of the first maximum value
array.argmax()

2

In [37]:
np.sum(array)

40

In [38]:
np.sqrt(array)

array([ 1.41421356,  0.        ,  3.        ,  2.        ,  2.23606798,
        2.44948974,  3.        ,  2.23606798,  0.        ])

In [39]:
np.tan(array) / np.cos(array)

array([  5.25064634,   0.        ,   0.49643358,  -1.77133417,
       -11.91739745,  -0.30307769,   0.49643358, -11.91739745,   0.        ])

In [87]:
array3 = np.random.rand(3,3)
array3_inv = np.linalg.inv(array3)
print(array3_inv)

[[ 1.59239255 -1.55449576  0.7238594 ]
 [-1.88947486  0.4118059   1.23726757]
 [ 1.07707243  2.39022947 -1.89303318]]


In [88]:
array3.dot(array3_inv) # OK

array([[  1.00000000e+00,   0.00000000e+00,  -1.11022302e-16],
       [ -1.11022302e-16,   1.00000000e+00,  -2.22044605e-16],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

## Slicing arrays

Récupérer des tranches de valeurs fonctionne de la même manière que pour les listes : 

In [40]:
array

array([2, 0, 9, 4, 5, 6, 9, 5, 0])

In [41]:
array[1:3]

array([0, 9])

In [42]:
array[1::2]

array([0, 4, 6, 5])

**Pay attention**: slides are views of the original array.

The data are to copied when a slide is made -> NumPy fast for slicing operations.

But it means that modification of their elements are reflected back in the original array!


In [71]:
a = np.arange(16).reshape((4,4))

print(a)

a[1:3,1:3] = -1
print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4 -1 -1  7]
 [ 8 -1 -1 11]
 [12 13 14 15]]


## Pay attention

* Operations that involve attributes or methods of `ndarray` occur *in-place*. While functions that take an `ndarray` as an argument return a *modified copy*.
* With NumPy ndarray, a=b creates a new reference to b, not a copy.

In [93]:
a = np.random.rand(5)
b = np.arange(5)
b = a # b is a new reference to a.
b[0] = 10
print(b)

[ 10.           0.94344595   0.92786359   0.17037004   0.20603176]


In [92]:
# Because b refers to a, modifyng b also modify a !
print(a)

[ 10.           0.23200632   0.06140214   0.89119267   0.10813223]


In [94]:
b=a.copy() 
b[0] = 20
print(b)
print(a) # a has not been modified.

[ 20.           0.94344595   0.92786359   0.17037004   0.20603176]
[ 10.           0.94344595   0.92786359   0.17037004   0.20603176]


## Broadcasting

Broadcasting rules describe how arrays with different dimensions and/or shapes can be used for computations.

The general rule is that: 2 dimensions are compatible when they are equal or when one of them is 1.

In [95]:
a = np.arange(3)
b = 5

In [96]:
a+b

array([5, 6, 7])

In [97]:
a = np.ones((3,3))
b = np.arange(3)
a+b

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

<div class='exercice'><h1>Exercice</h1>
Soit deux vecteur a et b, tels que shape(a)=(4,1) et shape(b)=(1,3). Calculer le produit exterieur a o b = a_i.b_j. Le resultat doit être de shape (4,3). 
</div>

In [104]:
a = np.arange(4).reshape(4,1) # reshapes into column vector
b = np.arange(3)
a*b

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

## Fancy indexing, masking

Slicing is great when indices follow a regulary pattern.

But when one want arbitrary indexes, this is known as fancy indexing: the index is an integer array or a list of integer.

This requires a copy of the original array (so a performance cost)

In [105]:
a = np.arange(10)
print(a)

index = [3,1,6]
print(a[index])

[0 1 2 3 4 5 6 7 8 9]
[3 1 6]




Masking is like fancy indexing, except that it must be a *Boolean* array (not a Python list!).

As with fancy indexing, the application of a mask to an array will produce a copy of the original data.


In [112]:
mask = np.array([0,1,0,1,1,0], dtype=bool)
a[mask]

array([1, 3, 4])

**Pay attention**: The following does not work as one could expect from Matlab behaviour !

In [113]:
a[[0,1,0,1,1,0]] # Here we use a Python list. 

array([0, 1, 0, 1, 1, 0])

<div class='exercice'><h1>Quizz</h1>
Pouvez-vous expliquer le dernier exemple ?
</div>

The mask can be generated in the indexing operation itself

In [108]:
a[a > 5]

array([6, 7, 8, 9])

It is also possible to combine masks with operators

In [109]:
a[(a>5) & (a<=8)]

array([6, 7, 8])

The NumPy `where()` function takes a Boolean array and return a tuple of the indices where the mask is True.

In [110]:
np.where(a > 5)

(array([6, 7, 8, 9]),)

In [114]:
a[np.where(a > 5)]

array([6, 7, 8, 9])

<div class='exercice'><h1>Exercice</h1>
Récupérez le courant plasma (signal SIPMES) pour le choc 47979 et tracez-le uniquement lorsque Ip>50 kA.
</div>